### ISSUE TITLE
Running `npm run watch fails`

### ISSUE THREAD

**Issue by oveddan** [stride-nyc/web-boilerplate-2016#2]
When running `npm run watch` or `npm test` (as instructed in the readme) you get the error:

```
> webapp-boilerplate@0.0.5 watch /Users/danoved/Source/opensource/dat-gui-react
> npm run test -- --single-run=false


> webapp-boilerplate@0.0.5 test /Users/danoved/Source/opensource/dat-gui-react
> NODE_ENV=test karma start karma.conf.js "--single-run=false"

29 12 2015 23:47:48.172:ERROR [config]: Invalid config file!
  /Users/danoved/Source/opensource/dat-gui-react/webpack.config.js:50
  entry : [`${PATHS.SOURCE}/app.jsx`]
           ^
SyntaxError: Unexpected token ILLEGAL
```

Is this because babel should be processing the webpack config file?

**Comment by imcnally** [comment]
Thanks @oveddan! I explicitly wrote webpack.config without es6 but forgot to change the template string. Both tasks were running fine on my machine. I'm wondering if my node version (4.2) was giving me that feature for free. 

Regardless, it's es6-less as of d0a3a06.
